print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $"))
percentage = 1+ (int(input("How much tip would you like to give? 10, 12, or 15?")) / 100)
people = int(input("How many people to split the bill?"))
should_pay = round(((total_bill * percentage)/people),2)
print(f"Each person should pay ${should_pay}")